

site_name: SamirDocs


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: index.md
- Implementation:
  - Querying ElasticSearch for Drug/Chemical Occurrence: 'implementation/chemical_drug_elastic_occurance/chemical_drug_elastic_occurance.md'
  - Visualizing Distribution of Data in Pubmed: 'implementation/Occurrence_Count_Plots/Occurrence_Count_Plots.md'
  - Generating Final Inputs for CaseOLAP: 'implementation/create_oxidative_stress_categories/create_oxidative_stress_categories.md'
  - Finding Common Pathways Used by Drugs: 'implementation/Explore_Drug_chemical_OxStress/Explore_Drug_chemical_OxStress.md'
  - Creating Drug/Chemical Co-Occurence GraphDB: 'implementation/Create_Drug_Cooccurance_Graph.md'
- Instruction:
  - Querying ElasticSearch in Python: 'instructions/Query_Python_Elastic.md'
  - Querying Neo4J in Python: 'instructions/Query_Neo4j_Python.md'
  - Export Neo4J Subgraph in Python: 'instructions/Export_Subgraph.md'
  - Import GraphML Subgraph to Neo4J in Python: 'instructions/Import_Subgraph.md'
- Notes:
  - Databases: 'notes/Databases.md'
  - ElasticSearch: 'notes/ElasticSearch.md'
  - Neo4J And Cypher: 'notes/neo4j.md'
  - DNA Repair Pathways: 'notes/DNA_Repair_Pathway_Notes/DNA_Repair_Pathways.md'




 
 
